version: '3.3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    ports:
      - 3306:3306
    restart:
      always